import {ScaledSheet} from 'react-native-size-matters';
import colors from '@SilalApp/common/assets/colors';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
  listenOrientationChange as lor,
  removeOrientationListener as rol,
} from 'react-native-responsive-screen-hooks';
import fonts from '@SilalApp/common/assets/fonts';
import {color} from 'react-native-reanimated';
import IsTablet from '@SilalApp/common/components/native/IsTablet';
const styles = ScaledSheet.create({
  title: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Poppins-Light',
    margin: 10,
  },
  single_order: {
    backgroundColor: 'white',
    marginHorizontal: 10,
    marginVertical: 5,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  filter_box: {
    flex: 1,
    justifyContent: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
  },
  filter: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: 40,
    width: 150,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  order_header: {
    flex: 1,
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  orderid_text: {
    fontSize: 15,
    color: '#CCD4D6',
    fontWeight: 'bold',
  },
  order_timer: {
    backgroundColor: '#F2A341',
    borderRadius: '0 0 5 5',
  },
  order_title: {
    width: '70%',
    fontSize: 17,
  },
  order_item: {
    flexDirection: 'row',
    marginTop: 20,
  },
  cross_icon: {
    color: '#CCD4D6',
    fontSize: 16,
  },
  more_order: {
    width: 60,
    backgroundColor: '#E6F4F2',
    padding: 3,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 30,
    marginTop: 5,
  },
  accept_btn: {
    backgroundColor: colors.primary,
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignItems: 'center',
  },
  accept_btn_txt: {
    color: 'white',
    fontSize: 15,
  },
  order_recve_name: {
    fontSize: 17,
    fontWeight: '400',
    color: 'black',
  },
  order_recve_phone_view: {
    flexDirection: 'row',
    marginTop: 20,
    alignItems: 'center',
  },
  order_recve_loc_view: {
    flexDirection: 'row',
    marginTop: 10,
    alignItems: 'center',
  },
  ready_btn: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 5,
    alignItems: 'center',
    paddingVertical: 10,
    justifyContent: 'center',
  },
  delivryby_btn: {
    backgroundColor: '#fdf1e3',
    padding: 5,
    borderRadius: 5,
  },
  delivryby_btn_txt: {
    color: '#F2A341',
  },
  all_orders: {
    backgroundColor: '#F2F4F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  all_orders_header: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    height: 50,
    backgroundColor: '#F2F4F5',
    padding: 10,
    marginVertical: 8,
  },
  render_all_orders: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: 'white',
    // padding: 10
  },
  render_all_order_single: {
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    height: '100%',
    width: '50%',
    alignSelf: 'flex-end',
    backgroundColor: 'white',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  orderid_text: {
    fontSize: 15,
    color: 'black',
    fontWeight: 'bold',
  },
  modal_header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modal_recuring: {
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    marginLeft: 20,
  },
  modal_fields: {
    flexDirection: 'row',
    marginVertical: 5,
    alignItems: 'center',
  },
  order_item: {
    flexDirection: 'row',
    marginTop: 20,
    alignItems: 'center',
  },
  modal_title_second: {
    color: 'black',
    fontSize: 15,
  },
  modal_title_first: {
    color: '#CCD4D6',
    fontSize: 15,
    width: 150,
  },
  archive_orders_tab: {
    borderBottomWidth: 4,
    height: 40,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  calndr_date: {
    backgroundColor: 'white',
    height: 40,
    width: 200,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  all_orders_heading_txt: {
    fontFamily: 'Lato-Bold',
  },
  toast: {
    backgroundColor: '#FFFFFF',
    // marginHorizontal:30,
    paddingVertical: 10,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },

  modal_data_heading: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: '#F2F4F5',
    borderRadius: 5,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  pagination_view: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    marginTop: 20,
    // backgroundColor:'red'
  },
  pagination_numbring: {
    width: 200,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  SwiperTextfg: {
    textAlign: 'center',
    paddingVertical: 3,
    color: '#002733',
    // borderRadius: 5,
  },
  SwiperTextbg: {
    textAlign: 'center',
    // paddingVertical: 3,
    color: '#FFFFFF',
    paddingHorizontal: 5,
    paddingVertical: 8,
    fontSize: 16,
  },
  rowBack: {
    height: 55,
    backgroundColor: '#fff',
  },
  BackButtons: {
    height: 60,
    width: 72,
    justifyContent: 'center',
    alignItems: 'center',
  },
  BackButtonsText: {
    color: '#fff',
    fontSize: 15,
    fontFamily: 'Lato-Medium',
  },
  ModalContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    // backgroundColor: 'rgba(0,0,0,0.8)'
  },
  ModeView: {
    height: 180,
    width: 410,
    backgroundColor: '#fff',
    borderRadius: 5,
    elevation: 0.2,
  },
  ModalTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 13,
  },
  ModalHeading: {
    color: '#414342',
    fontSize: 17,
    fontFamily: 'Poppins-SemiBold',
  },
  ModalParagraph: {
    color: '#4C6870',
    fontFamily: 'Lato-Regular',
    paddingHorizontal: 20,
    fontSize: 15,
    marginVertical: 15,
  },
  ModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '96%',
    alignSelf: 'center',
    marginVertical: 5,
  },
  Buttonss: {
    width: '45%',
    height: 45,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 10,
  },
  DeleteModal: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 15,
  },
  ModalContainerPreview: {
    width: '40%',
    height: '100%',
    backgroundColor: '#fff',
    position: 'absolute',
    right: 0,
    paddingVertical: 20,

    // backgroundColor: 'rgba(0,0,0,0.5)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 1,
  },
  CrossPreview: {
    fontSize: 25,
    color: '#000000',
    position: 'absolute',
    right: 15,
    top: 20,
  },
  dropdownbox: {
    height: 50,
    width: '100%',
    borderWidth: 1,
    borderRadius: 5,
    marginVertical: 5,
    borderColor: '#f1f1f1',
  },
  ShowmodalOpenButton: {
    height: 30,
    width: 40,
    flexDirection: 'row-reverse',
    width: '100%',
    marginVertical: 5,
    marginRight: -24,
  },
  closeShowmodalicon: {
    fontSize: 30,
    color: '#002733',
  },
  SaveButton: {
    backgroundColor: colors.primary,
    width: '80%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: 40,
    borderRadius: 5,
  },
  Savetext: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
  },
  ImageMoadalMain: {
    height: 200,
    width: 330,
    justifyContent: 'center',
    alignSelf: 'center',
    resizeMode: 'contain',
    zIndex: 0,
    borderRadius: 5,
  },
  IconOnMainImageView: {
    flexDirection: 'row',
    position: 'absolute',
    right: 0,
    top: 220,
    right: 50,
    elevation: 1,
  },
  InnerViewMainImage: {
    backgroundColor: '#fff',
    height: 33,
    width: 35,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    position: 'absolute',
    bottom: 10,
    right: 8,
  },
  IconePencilMain: {
    fontSize: 20,
    color: '#4C6870',
  },
  ModalSubTitle: {
    color: '#002733',
    fontSize: 17,
    fontFamily: 'Poppins-SemiBold',
  },
  dropDownModalTitle: {
    fontSize: 12,
    fontFamily: 'Lato-Semibold',
    color: '#002733',
    paddingVertical: 4,
  },
  TextInputMAinView: {
    fontFamily: 'Lato-Regular',
    fontSize: 17,
    width: '100%',
    height: 150,
    borderWidth: 1,
    borderColor: '#f1f1f1',
    color: '#002733',
    borderRadius: 5,
    paddingVertical: 15,
    paddingHorizontal: 10,
  },
  CalViewFaltModal: {
    width: '45%',
    marginHorizontal: 10,
    marginVertical: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#f1f1f1',
  },
  CalInputFaltModal: {
    fontSize: 17,
    fontFamily: 'Lato-Regular',
    paddingHorizontal: 8,
    height: 40,
  },
  AddViewModal: {
    color: '#002733',
    fontSize: 17,
    fontFamily: 'Poppins-SemiBold',
    paddingVertical: 10,
  },
  grayViewContainer: {
    width: '100%',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#F2F4F5',
    borderRadius: 5,
    marginBottom: 20,
    paddingTop: 10,
    paddingHorizontal: 8,
  },
  ToppingTitle: {
    fontSize: 14,
    color: '#002733',
    paddingHorizontal: 5,
    width: 280,
    paddingVertical: 4,
  },
  WhitePencilBkgView: {
    backgroundColor: '#4C6870',
    height: 30,
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  FlatLettuce: {
    width: '27%',
    marginHorizontal: 3,
    marginVertical: 5,
    borderRadius: 5,
    borderWidth: 1,
    backgroundColor: '#CCD4D6',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    borderColor: '#CCD4D6',
  },
  TextStyleFlatModal: {
    color: '#4C6870',
    fontFamily: 'Lato-Regular',
  },
  BottomButtonModal: {
    position: 'absolute',
    right: 1,
    bottom: -40,
  },
  dropdownbox1: {
    height: 40,
    width: '100%',
    elevation: 0.7,
    borderRadius: 5,
    borderColor: '#C2CCCF',
    marginVertical: 5,

    borderWidth: 1,
  },
  Container: {
    height: '100%',
    paddingHorizontal: 20,
    backgroundColor: '#f1f1f1',
     
  },
  secondaryContainer: {
    width: '100%',
    alignSelf: 'center',
  },
  headerComponent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 5,
    alignItems: 'center',
  },
  headerComponentMobile: {
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    marginVertical: 5,
    // alignItems: 'center',
    marginHorizontal:10
  },
  backButtonpage: {
    fontSize: 25,
    color: '#002733',
    fontFamily: 'Poppins-Bold',
  },
  backButtonpage: {
    fontSize: '20@s',
    fontSize: 25,
    color: '#002733',
    fontFamily: 'Poppins-Bold',
  },
  backButtonpagemobile: {
    fontSize: '10@s',
    fontSize: 25,
    color: '#002733',
    fontFamily: 'Poppins-Bold',
  },
  backButtonpageArrow: {
    color: '#002733',
    fontFamily: 'Poppins-Bold',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '16@s',
  },
  backButtonpageArrowmobile: {
    fontSize: '25@s',
    color: '#002733',
    fontFamily: 'Poppins-Bold',
    paddingTop: 3,
  },
});
export default styles;
