export const data=[
  { alpha2Code: "AF", callingCodes: ["93"], id: 0, name: "Afghanistan" },
  { alpha2Code: "AX", callingCodes: ["358"], id: 1, name: "Åland Islands" },
  { alpha2Code: "AL", callingCodes: ["355"], id: 2, name: "Albania" },
  { alpha2Code: "DZ", callingCodes: ["213"], id: 3, name: "Algeria" },
  { alpha2Code: "AS", callingCodes: ["1"], id: 4, name: "American Samoa" },
  { alpha2Code: "AD", callingCodes: ["376"], id: 5, name: "Andorra" },
  { alpha2Code: "AO", callingCodes: ["244"], id: 6, name: "Angola" },
  { alpha2Code: "AI", callingCodes: ["1"], id: 7, name: "Anguilla" },
  { alpha2Code: "AQ", callingCodes: ["672"], id: 8, name: "Antarctica" },
  { alpha2Code: "AG", callingCodes: ["1"], id: 9, name: "Antigua and Barbuda" },
  { alpha2Code: "AR", callingCodes: ["54"], id: 10, name: "Argentina" },
  { alpha2Code: "AM", callingCodes: ["374"], id: 11, name: "Armenia" },
  { alpha2Code: "AW", callingCodes: ["297"], id: 12, name: "Aruba" },
  { alpha2Code: "AU", callingCodes: ["61"], id: 13, name: "Australia" },
  { alpha2Code: "AT", callingCodes: ["43"], id: 14, name: "Austria" },
  { alpha2Code: "AZ", callingCodes: ["994"], id: 15, name: "Azerbaijan" },
  { alpha2Code: "BS", callingCodes: ["1"], id: 16, name: "Bahamas" },
  { alpha2Code: "BH", callingCodes: ["973"], id: 17, name: "Bahrain" },
  { alpha2Code: "BD", callingCodes: ["880"], id: 18, name: "Bangladesh" },
  { alpha2Code: "BB", callingCodes: ["1"], id: 19, name: "Barbados" },
  { alpha2Code: "BY", callingCodes: ["375"], id: 20, name: "Belarus" },
  { alpha2Code: "BE", callingCodes: ["32"], id: 21, name: "Belgium" },
  { alpha2Code: "BZ", callingCodes: ["501"], id: 22, name: "Belize" },
  { alpha2Code: "BJ", callingCodes: ["229"], id: 23, name: "Benin" },
  { alpha2Code: "BM", callingCodes: ["1"], id: 24, name: "Bermuda" },
  { alpha2Code: "BT", callingCodes: ["975"], id: 25, name: "Bhutan" },
  {
    alpha2Code: "BO",
    callingCodes: ["591"],
    id: 26,
    name: "Bolivia (Plurinational State of)",
  },
  {
    alpha2Code: "BQ",
    callingCodes: ["599"],
    id: 27,
    name: "Bonaire, Sint Eustatius and Saba",
  },
  {
    alpha2Code: "BA",
    callingCodes: ["387"],
    id: 28,
    name: "Bosnia and Herzegovina",
  },
  { alpha2Code: "BW", callingCodes: ["267"], id: 29, name: "Botswana" },
  { alpha2Code: "BV", callingCodes: ["47"], id: 30, name: "Bouvet Island" },
  { alpha2Code: "BR", callingCodes: ["55"], id: 31, name: "Brazil" },
  {
    alpha2Code: "IO",
    callingCodes: ["246"],
    id: 32,
    name: "British Indian Ocean Territory",
  },
  {
    alpha2Code: "UM",
    callingCodes: ["246"],
    id: 33,
    name: "United States Minor Outlying Islands",
  },
  {
    alpha2Code: "VG",
    callingCodes: ["1"],
    id: 34,
    name: "Virgin Islands (British)",
  },
  {
    alpha2Code: "VI",
    callingCodes: ["1 340"],
    id: 35,
    name: "Virgin Islands (U.S.)",
  },
  {
    alpha2Code: "BN",
    callingCodes: ["673"],
    id: 36,
    name: "Brunei Darussalam",
  },
  { alpha2Code: "BG", callingCodes: ["359"], id: 37, name: "Bulgaria" },
  { alpha2Code: "BF", callingCodes: ["226"], id: 38, name: "Burkina Faso" },
  { alpha2Code: "BI", callingCodes: ["257"], id: 39, name: "Burundi" },
  { alpha2Code: "KH", callingCodes: ["855"], id: 40, name: "Cambodia" },
  { alpha2Code: "CM", callingCodes: ["237"], id: 41, name: "Cameroon" },
  { alpha2Code: "CA", callingCodes: ["1"], id: 42, name: "Canada" },
  { alpha2Code: "CV", callingCodes: ["238"], id: 43, name: "Cabo Verde" },
  { alpha2Code: "KY", callingCodes: ["1"], id: 44, name: "Cayman Islands" },
  {
    alpha2Code: "CF",
    callingCodes: ["236"],
    id: 45,
    name: "Central African Republic",
  },
  { alpha2Code: "TD", callingCodes: ["235"], id: 46, name: "Chad" },
  { alpha2Code: "CL", callingCodes: ["56"], id: 47, name: "Chile" },
  { alpha2Code: "CN", callingCodes: ["86"], id: 48, name: "China" },
  { alpha2Code: "CX", callingCodes: ["61"], id: 49, name: "Christmas Island" },
  {
    alpha2Code: "CC",
    callingCodes: ["61"],
    id: 50,
    name: "Cocos (Keeling) Islands",
  },
  { alpha2Code: "CO", callingCodes: ["57"], id: 51, name: "Colombia" },
  { alpha2Code: "KM", callingCodes: ["269"], id: 52, name: "Comoros" },
  { alpha2Code: "CG", callingCodes: ["242"], id: 53, name: "Congo" },
  {
    alpha2Code: "CD",
    callingCodes: ["243"],
    id: 54,
    name: "Congo (Democratic Republic of the)",
  },
  { alpha2Code: "CK", callingCodes: ["682"], id: 55, name: "Cook Islands" },
  { alpha2Code: "CR", callingCodes: ["506"], id: 56, name: "Costa Rica" },
  { alpha2Code: "HR", callingCodes: ["385"], id: 57, name: "Croatia" },
  { alpha2Code: "CU", callingCodes: ["53"], id: 58, name: "Cuba" },
  { alpha2Code: "CW", callingCodes: ["599"], id: 59, name: "Curaçao" },
  { alpha2Code: "CY", callingCodes: ["357"], id: 60, name: "Cyprus" },
  { alpha2Code: "CZ", callingCodes: ["420"], id: 61, name: "Czech Republic" },
  { alpha2Code: "DK", callingCodes: ["45"], id: 62, name: "Denmark" },
  { alpha2Code: "DJ", callingCodes: ["253"], id: 63, name: "Djibouti" },
  { alpha2Code: "DM", callingCodes: ["1"], id: 64, name: "Dominica" },
  { alpha2Code: "DO", callingCodes: ["1"], id: 65, name: "Dominican Republic" },
  { alpha2Code: "EC", callingCodes: ["593"], id: 66, name: "Ecuador" },
  { alpha2Code: "EG", callingCodes: ["20"], id: 67, name: "Egypt" },
  { alpha2Code: "SV", callingCodes: ["503"], id: 68, name: "El Salvador" },
  {
    alpha2Code: "GQ",
    callingCodes: ["240"],
    id: 69,
    name: "Equatorial Guinea",
  },
  { alpha2Code: "ER", callingCodes: ["291"], id: 70, name: "Eritrea" },
  { alpha2Code: "EE", callingCodes: ["372"], id: 71, name: "Estonia" },
  { alpha2Code: "ET", callingCodes: ["251"], id: 72, name: "Ethiopia" },
  {
    alpha2Code: "FK",
    callingCodes: ["500"],
    id: 73,
    name: "Falkland Islands (Malvinas)",
  },
  { alpha2Code: "FO", callingCodes: ["298"], id: 74, name: "Faroe Islands" },
  { alpha2Code: "FJ", callingCodes: ["679"], id: 75, name: "Fiji" },
  { alpha2Code: "FI", callingCodes: ["358"], id: 76, name: "Finland" },
  { alpha2Code: "FR", callingCodes: ["33"], id: 77, name: "France" },
  { alpha2Code: "GF", callingCodes: ["594"], id: 78, name: "French Guiana" },
  { alpha2Code: "PF", callingCodes: ["689"], id: 79, name: "French Polynesia" },
  {
    alpha2Code: "TF",
    callingCodes: ["262"],
    id: 80,
    name: "French Southern Territories",
  },
  { alpha2Code: "GA", callingCodes: ["241"], id: 81, name: "Gabon" },
  { alpha2Code: "GM", callingCodes: ["220"], id: 82, name: "Gambia" },
  { alpha2Code: "GE", callingCodes: ["995"], id: 83, name: "Georgia" },
  { alpha2Code: "DE", callingCodes: ["49"], id: 84, name: "Germany" },
  { alpha2Code: "GH", callingCodes: ["233"], id: 85, name: "Ghana" },
  { alpha2Code: "GI", callingCodes: ["350"], id: 86, name: "Gibraltar" },
  { alpha2Code: "GR", callingCodes: ["30"], id: 87, name: "Greece" },
  { alpha2Code: "GL", callingCodes: ["299"], id: 88, name: "Greenland" },
  { alpha2Code: "GD", callingCodes: ["1"], id: 89, name: "Grenada" },
  { alpha2Code: "GP", callingCodes: ["590"], id: 90, name: "Guadeloupe" },
  { alpha2Code: "GU", callingCodes: ["1"], id: 91, name: "Guam" },
  { alpha2Code: "GT", callingCodes: ["502"], id: 92, name: "Guatemala" },
  { alpha2Code: "GG", callingCodes: ["44"], id: 93, name: "Guernsey" },
  { alpha2Code: "GN", callingCodes: ["224"], id: 94, name: "Guinea" },
  { alpha2Code: "GW", callingCodes: ["245"], id: 95, name: "Guinea-Bissau" },
  { alpha2Code: "GY", callingCodes: ["592"], id: 96, name: "Guyana" },
  { alpha2Code: "HT", callingCodes: ["509"], id: 97, name: "Haiti" },
  {
    alpha2Code: "HM",
    callingCodes: ["672"],
    id: 98,
    name: "Heard Island and McDonald Islands",
  },
  { alpha2Code: "VA", callingCodes: ["379"], id: 99, name: "Vatican City" },
  { alpha2Code: "HN", callingCodes: ["504"], id: 100, name: "Honduras" },
  { alpha2Code: "HU", callingCodes: ["36"], id: 101, name: "Hungary" },
  { alpha2Code: "HK", callingCodes: ["852"], id: 102, name: "Hong Kong" },
  { alpha2Code: "IS", callingCodes: ["354"], id: 103, name: "Iceland" },
  { alpha2Code: "IN", callingCodes: ["91"], id: 104, name: "India" },
  { alpha2Code: "ID", callingCodes: ["62"], id: 105, name: "Indonesia" },
  { alpha2Code: "CI", callingCodes: ["225"], id: 106, name: "Ivory Coast" },
  {
    alpha2Code: "IR",
    callingCodes: ["98"],
    id: 107,
    name: "Iran (Islamic Republic of)",
  },
  { alpha2Code: "IQ", callingCodes: ["964"], id: 108, name: "Iraq" },
  { alpha2Code: "IE", callingCodes: ["353"], id: 109, name: "Ireland" },
  { alpha2Code: "IM", callingCodes: ["44"], id: 110, name: "Isle of Man" },
  { alpha2Code: "IL", callingCodes: ["972"], id: 111, name: "Israel" },
  { alpha2Code: "IT", callingCodes: ["39"], id: 112, name: "Italy" },
  { alpha2Code: "JM", callingCodes: ["1"], id: 113, name: "Jamaica" },
  { alpha2Code: "JP", callingCodes: ["81"], id: 114, name: "Japan" },
  { alpha2Code: "JE", callingCodes: ["44"], id: 115, name: "Jersey" },
  { alpha2Code: "JO", callingCodes: ["962"], id: 116, name: "Jordan" },
  { alpha2Code: "KZ", callingCodes: ["76", "77"], id: 117, name: "Kazakhstan" },
  { alpha2Code: "KE", callingCodes: ["254"], id: 118, name: "Kenya" },
  { alpha2Code: "KI", callingCodes: ["686"], id: 119, name: "Kiribati" },
  { alpha2Code: "KW", callingCodes: ["965"], id: 120, name: "Kuwait" },
  { alpha2Code: "KG", callingCodes: ["996"], id: 121, name: "Kyrgyzstan" },
  {
    alpha2Code: "LA",
    callingCodes: ["856"],
    id: 122,
    name: "Lao People's Democratic Republic",
  },
  { alpha2Code: "LV", callingCodes: ["371"], id: 123, name: "Latvia" },
  { alpha2Code: "LB", callingCodes: ["961"], id: 124, name: "Lebanon" },
  { alpha2Code: "LS", callingCodes: ["266"], id: 125, name: "Lesotho" },
  { alpha2Code: "LR", callingCodes: ["231"], id: 126, name: "Liberia" },
  { alpha2Code: "LY", callingCodes: ["218"], id: 127, name: "Libya" },
  { alpha2Code: "LI", callingCodes: ["423"], id: 128, name: "Liechtenstein" },
  { alpha2Code: "LT", callingCodes: ["370"], id: 129, name: "Lithuania" },
  { alpha2Code: "LU", callingCodes: ["352"], id: 130, name: "Luxembourg" },
  { alpha2Code: "MO", callingCodes: ["853"], id: 131, name: "Macao" },
  { alpha2Code: "MK", callingCodes: ["389"], id: 132, name: "North Macedonia" },
  { alpha2Code: "MG", callingCodes: ["261"], id: 133, name: "Madagascar" },
  { alpha2Code: "MW", callingCodes: ["265"], id: 134, name: "Malawi" },
  { alpha2Code: "MY", callingCodes: ["60"], id: 135, name: "Malaysia" },
  { alpha2Code: "MV", callingCodes: ["960"], id: 136, name: "Maldives" },
  { alpha2Code: "ML", callingCodes: ["223"], id: 137, name: "Mali" },
  { alpha2Code: "MT", callingCodes: ["356"], id: 138, name: "Malta" },
  {
    alpha2Code: "MH",
    callingCodes: ["692"],
    id: 139,
    name: "Marshall Islands",
  },
  { alpha2Code: "MQ", callingCodes: ["596"], id: 140, name: "Martinique" },
  { alpha2Code: "MR", callingCodes: ["222"], id: 141, name: "Mauritania" },
  { alpha2Code: "MU", callingCodes: ["230"], id: 142, name: "Mauritius" },
  { alpha2Code: "YT", callingCodes: ["262"], id: 143, name: "Mayotte" },
  { alpha2Code: "MX", callingCodes: ["52"], id: 144, name: "Mexico" },
  {
    alpha2Code: "FM",
    callingCodes: ["691"],
    id: 145,
    name: "Micronesia (Federated States of)",
  },
  {
    alpha2Code: "MD",
    callingCodes: ["373"],
    id: 146,
    name: "Moldova (Republic of)",
  },
  { alpha2Code: "MC", callingCodes: ["377"], id: 147, name: "Monaco" },
  { alpha2Code: "MN", callingCodes: ["976"], id: 148, name: "Mongolia" },
  { alpha2Code: "ME", callingCodes: ["382"], id: 149, name: "Montenegro" },
  { alpha2Code: "MS", callingCodes: ["1"], id: 150, name: "Montserrat" },
  { alpha2Code: "MA", callingCodes: ["212"], id: 151, name: "Morocco" },
  { alpha2Code: "MZ", callingCodes: ["258"], id: 152, name: "Mozambique" },
  { alpha2Code: "MM", callingCodes: ["95"], id: 153, name: "Myanmar" },
  { alpha2Code: "NA", callingCodes: ["264"], id: 154, name: "Namibia" },
  { alpha2Code: "NR", callingCodes: ["674"], id: 155, name: "Nauru" },
  { alpha2Code: "NP", callingCodes: ["977"], id: 156, name: "Nepal" },
  { alpha2Code: "NL", callingCodes: ["31"], id: 157, name: "Netherlands" },
  { alpha2Code: "NC", callingCodes: ["687"], id: 158, name: "New Caledonia" },
  { alpha2Code: "NZ", callingCodes: ["64"], id: 159, name: "New Zealand" },
  { alpha2Code: "NI", callingCodes: ["505"], id: 160, name: "Nicaragua" },
  { alpha2Code: "NE", callingCodes: ["227"], id: 161, name: "Niger" },
  { alpha2Code: "NG", callingCodes: ["234"], id: 162, name: "Nigeria" },
  { alpha2Code: "NU", callingCodes: ["683"], id: 163, name: "Niue" },
  { alpha2Code: "NF", callingCodes: ["672"], id: 164, name: "Norfolk Island" },
  {
    alpha2Code: "KP",
    callingCodes: ["850"],
    id: 165,
    name: "Korea (Democratic People's Republic of)",
  },
  {
    alpha2Code: "MP",
    callingCodes: ["1"],
    id: 166,
    name: "Northern Mariana Islands",
  },
  { alpha2Code: "NO", callingCodes: ["47"], id: 167, name: "Norway" },
  { alpha2Code: "OM", callingCodes: ["968"], id: 168, name: "Oman" },
  { alpha2Code: "PK", callingCodes: ["92"], id: 169, name: "Pakistan" },
  { alpha2Code: "PW", callingCodes: ["680"], id: 170, name: "Palau" },
  {
    alpha2Code: "PS",
    callingCodes: ["970"],
    id: 171,
    name: "Palestine, State of",
  },
  { alpha2Code: "PA", callingCodes: ["507"], id: 172, name: "Panama" },
  {
    alpha2Code: "PG",
    callingCodes: ["675"],
    id: 173,
    name: "Papua New Guinea",
  },
  { alpha2Code: "PY", callingCodes: ["595"], id: 174, name: "Paraguay" },
  { alpha2Code: "PE", callingCodes: ["51"], id: 175, name: "Peru" },
  { alpha2Code: "PH", callingCodes: ["63"], id: 176, name: "Philippines" },
  { alpha2Code: "PN", callingCodes: ["64"], id: 177, name: "Pitcairn" },
  { alpha2Code: "PL", callingCodes: ["48"], id: 178, name: "Poland" },
  { alpha2Code: "PT", callingCodes: ["351"], id: 179, name: "Portugal" },
  { alpha2Code: "PR", callingCodes: ["1"], id: 180, name: "Puerto Rico" },
  { alpha2Code: "QA", callingCodes: ["974"], id: 181, name: "Qatar" },
  {
    alpha2Code: "XK",
    callingCodes: ["383"],
    id: 182,
    name: "Republic of Kosovo",
  },
  { alpha2Code: "RE", callingCodes: ["262"], id: 183, name: "Réunion" },
  { alpha2Code: "RO", callingCodes: ["40"], id: 184, name: "Romania" },
  {
    alpha2Code: "RU",
    callingCodes: ["7"],
    id: 185,
    name: "Russian Federation",
  },
  { alpha2Code: "RW", callingCodes: ["250"], id: 186, name: "Rwanda" },
  {
    alpha2Code: "BL",
    callingCodes: ["590"],
    id: 187,
    name: "Saint Barthélemy",
  },
  {
    alpha2Code: "SH",
    callingCodes: ["290"],
    id: 188,
    name: "Saint Helena, Ascension and Tristan da Cunha",
  },
  {
    alpha2Code: "KN",
    callingCodes: ["1"],
    id: 189,
    name: "Saint Kitts and Nevis",
  },
  { alpha2Code: "LC", callingCodes: ["1"], id: 190, name: "Saint Lucia" },
  {
    alpha2Code: "MF",
    callingCodes: ["590"],
    id: 191,
    name: "Saint Martin (French part)",
  },
  {
    alpha2Code: "PM",
    callingCodes: ["508"],
    id: 192,
    name: "Saint Pierre and Miquelon",
  },
  {
    alpha2Code: "VC",
    callingCodes: ["1"],
    id: 193,
    name: "Saint Vincent and the Grenadines",
  },
  { alpha2Code: "WS", callingCodes: ["685"], id: 194, name: "Samoa" },
  { alpha2Code: "SM", callingCodes: ["378"], id: 195, name: "San Marino" },
  {
    alpha2Code: "ST",
    callingCodes: ["239"],
    id: 196,
    name: "Sao Tome and Principe",
  },
  { alpha2Code: "SA", callingCodes: ["966"], id: 197, name: "Saudi Arabia" },
  { alpha2Code: "SN", callingCodes: ["221"], id: 198, name: "Senegal" },
  { alpha2Code: "RS", callingCodes: ["381"], id: 199, name: "Serbia" },
  { alpha2Code: "SC", callingCodes: ["248"], id: 200, name: "Seychelles" },
  { alpha2Code: "SL", callingCodes: ["232"], id: 201, name: "Sierra Leone" },
  { alpha2Code: "SG", callingCodes: ["65"], id: 202, name: "Singapore" },
  {
    alpha2Code: "SX",
    callingCodes: ["1"],
    id: 203,
    name: "Sint Maarten (Dutch part)",
  },
  { alpha2Code: "SK", callingCodes: ["421"], id: 204, name: "Slovakia" },
  { alpha2Code: "SI", callingCodes: ["386"], id: 205, name: "Slovenia" },
  { alpha2Code: "SB", callingCodes: ["677"], id: 206, name: "Solomon Islands" },
  { alpha2Code: "SO", callingCodes: ["252"], id: 207, name: "Somalia" },
  { alpha2Code: "ZA", callingCodes: ["27"], id: 208, name: "South Africa" },
  {
    alpha2Code: "GS",
    callingCodes: ["500"],
    id: 209,
    name: "South Georgia and the South Sandwich Islands",
  },
  {
    alpha2Code: "KR",
    callingCodes: ["82"],
    id: 210,
    name: "Korea (Republic of)",
  },
  { alpha2Code: "ES", callingCodes: ["34"], id: 211, name: "Spain" },
  { alpha2Code: "LK", callingCodes: ["94"], id: 212, name: "Sri Lanka" },
  { alpha2Code: "SD", callingCodes: ["249"], id: 213, name: "Sudan" },
  { alpha2Code: "SS", callingCodes: ["211"], id: 214, name: "South Sudan" },
  { alpha2Code: "SR", callingCodes: ["597"], id: 215, name: "Suriname" },
  {
    alpha2Code: "SJ",
    callingCodes: ["47"],
    id: 216,
    name: "Svalbard and Jan Mayen",
  },
  { alpha2Code: "SZ", callingCodes: ["268"], id: 217, name: "Swaziland" },
  { alpha2Code: "SE", callingCodes: ["46"], id: 218, name: "Sweden" },
  { alpha2Code: "CH", callingCodes: ["41"], id: 219, name: "Switzerland" },
  {
    alpha2Code: "SY",
    callingCodes: ["963"],
    id: 220,
    name: "Syrian Arab Republic",
  },
  { alpha2Code: "TW", callingCodes: ["886"], id: 221, name: "Taiwan" },
  { alpha2Code: "TJ", callingCodes: ["992"], id: 222, name: "Tajikistan" },
  {
    alpha2Code: "TZ",
    callingCodes: ["255"],
    id: 223,
    name: "Tanzania, United Republic of",
  },
  { alpha2Code: "TH", callingCodes: ["66"], id: 224, name: "Thailand" },
  { alpha2Code: "TL", callingCodes: ["670"], id: 225, name: "Timor-Leste" },
  { alpha2Code: "TG", callingCodes: ["228"], id: 226, name: "Togo" },
  { alpha2Code: "TK", callingCodes: ["690"], id: 227, name: "Tokelau" },
  { alpha2Code: "TO", callingCodes: ["676"], id: 228, name: "Tonga" },
  {
    alpha2Code: "TT",
    callingCodes: ["1"],
    id: 229,
    name: "Trinidad and Tobago",
  },
  { alpha2Code: "TN", callingCodes: ["216"], id: 230, name: "Tunisia" },
  { alpha2Code: "TR", callingCodes: ["90"], id: 231, name: "Turkey" },
  { alpha2Code: "TM", callingCodes: ["993"], id: 232, name: "Turkmenistan" },
  {
    alpha2Code: "TC",
    callingCodes: ["1"],
    id: 233,
    name: "Turks and Caicos Islands",
  },
  { alpha2Code: "TV", callingCodes: ["688"], id: 234, name: "Tuvalu" },
  { alpha2Code: "UG", callingCodes: ["256"], id: 235, name: "Uganda" },
  { alpha2Code: "UA", callingCodes: ["380"], id: 236, name: "Ukraine" },
  {
    alpha2Code: "AE",
    callingCodes: ["971"],
    id: 237,
    name: "United Arab Emirates",
  },
  {
    alpha2Code: "GB",
    callingCodes: ["44"],
    id: 238,
    name: "United Kingdom of Great Britain and Northern Ireland",
  },
  {
    alpha2Code: "US",
    callingCodes: ["1"],
    id: 239,
    name: "United States of America",
  },
  { alpha2Code: "UY", callingCodes: ["598"], id: 240, name: "Uruguay" },
  { alpha2Code: "UZ", callingCodes: ["998"], id: 241, name: "Uzbekistan" },
  { alpha2Code: "VU", callingCodes: ["678"], id: 242, name: "Vanuatu" },
  {
    alpha2Code: "VE",
    callingCodes: ["58"],
    id: 243,
    name: "Venezuela (Bolivarian Republic of)",
  },
  { alpha2Code: "VN", callingCodes: ["84"], id: 244, name: "Vietnam" },
  {
    alpha2Code: "WF",
    callingCodes: ["681"],
    id: 245,
    name: "Wallis and Futuna",
  },
  { alpha2Code: "EH", callingCodes: ["212"], id: 246, name: "Western Sahara" },
  { alpha2Code: "YE", callingCodes: ["967"], id: 247, name: "Yemen" },
  { alpha2Code: "ZM", callingCodes: ["260"], id: 248, name: "Zambia" },
  { alpha2Code: "ZW", callingCodes: ["263"], id: 249, name: "Zimbabwe" },
];
